osx_image: xcode10
language: swift
install:
  - bundle install
  - bundle exec pod repo update --silent
  - bundle exec pod install
script:
  - bundle exec fastlane tests
after_success:
#  - bundle exec fastlane coverage
  - bash <(curl -s https://codecov.io/bash)
